apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80   # in port Kubernetes
      targetPort: 3000  # container port
      nodePort: 30080
  type: NodePort
